# Generated by Django 4.2.4 on 2023-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUploadRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("number_of_entries", models.IntegerField()),
            ],
        ),
    ]
