# Generated by Django 4.2.4 on 2023-08-09 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_shiftregister"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShiftRegister",
            new_name="EscalaRecord",
        ),
        migrations.RenameModel(
            old_name="FileUploadRegister",
            new_name="FileUploadRecord",
        ),
    ]
